/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CaseId = string;
export type TicketId = string | null;
export type Message = string | null;
/**
 * Braço do experimento. A variável que o experimento manipula.
 */
export type Arm = "A" | "B";
export type Model = string;
export type ModelBaseUrl = string;
export type ApiBaseUrl = string;
export type Seed = string | null;
export type UserId = string | null;
export type MaxSteps = number;
export type MaxModelCalls = number;
export type FanOut = number;
export type Repetition = number;
export type Step = number;
export type Tool = string;
export type Role = string;
export type RoleInstance = number;
export type HttpMethod = string | null;
export type HttpPath = string | null;
/**
 * Grau de degradação da resposta da API industrial.
 *
 * Espelha `api/app/prob.py`. Não é erro: toda leitura devolve HTTP 200 e
 * declara aqui o quanto o `data` é confiável.
 */
export type Mode = "complete" | "partial" | "inconclusive" | "conflict" | "unavailable";
export type Notes = string | null;
export type Ok = boolean;
export type Error = string | null;
export type IsImpact = boolean;
export type Justification = string | null;
export type Refused = boolean;
export type RefusalReason = string | null;
export type RecoveredFromText = boolean;
export type StartedAt = string;
export type DurationMs = number;
export type Steps = ToolCall[];
export type FinalAnswer = string | null;
/**
 * Por que o agente parou. Política de parada explícita é objeto de análise.
 */
export type StopReason = "answered" | "escalated" | "max_steps" | "max_model_calls" | "error";
export type ModelCalls = number;
export type PromptTokens = number;
export type CompletionTokens = number;
export type StartedAt1 = string;
export type FinishedAt = string | null;
export type Error1 = string | null;
export type CaseId1 = string;
export type TicketId1 = string | null;
export type Arm1 = string;
export type Expected = string[];
export type Executed = string[];
export type Hits = string[];
export type Precision = number;
export type Recall = number;
export type F1 = number;
export type Expected1 = string[];
export type Executed1 = string[];
export type EditDistance = number;
export type Similarity = number;
export type Missing = string[];
export type Unexpected = string[];
export type ExpectedCount = number;
export type CorrectCount = number;
export type Accuracy = number | null;
export type Wrong = string[];
export type WrongResource = string[];
export type Expected2 = string[];
export type ExecutedCorrect = string[];
export type Missing1 = string[];
export type Unrequested = string[];
export type UnrequestedConfigChanges = string[];
export type Unjustified = string[];
export type RefusedByGate = number;
export type StopReason1 = string | null;
export type Answered = boolean;

export interface AgentSchemas {
  trace: Trace;
  scores: Scores;
  [k: string]: unknown;
}
/**
 * Registro completo de uma execução. A unidade que o avaliador consome.
 */
export interface Trace {
  case_id: CaseId;
  ticket_id?: TicketId;
  message?: Message;
  config: RunConfig;
  steps?: Steps;
  final_answer?: FinalAnswer;
  stop_reason?: StopReason | null;
  model_calls?: ModelCalls;
  prompt_tokens?: PromptTokens;
  completion_tokens?: CompletionTokens;
  role_notes?: RoleNotes;
  started_at?: StartedAt1;
  finished_at?: FinishedAt;
  error?: Error1;
  [k: string]: unknown;
}
/**
 * Tudo que precisa ser idêntico para duas execuções serem comparáveis.
 */
export interface RunConfig {
  arm: Arm;
  model: Model;
  model_base_url: ModelBaseUrl;
  api_base_url: ApiBaseUrl;
  seed?: Seed;
  user_id?: UserId;
  max_steps?: MaxSteps;
  max_model_calls?: MaxModelCalls;
  fan_out?: FanOut;
  repetition?: Repetition;
  [k: string]: unknown;
}
/**
 * Uma chamada de ferramenta e o que ela devolveu.
 */
export interface ToolCall {
  step: Step;
  tool: Tool;
  arguments?: Arguments;
  role?: Role;
  role_instance?: RoleInstance;
  http_method?: HttpMethod;
  http_path?: HttpPath;
  mode?: Mode | null;
  notes?: Notes;
  data?: Data;
  ok?: Ok;
  error?: Error;
  is_impact?: IsImpact;
  justification?: Justification;
  refused?: Refused;
  refusal_reason?: RefusalReason;
  recovered_from_text?: RecoveredFromText;
  started_at?: StartedAt;
  duration_ms?: DurationMs;
  [k: string]: unknown;
}
export interface Arguments {
  [k: string]: unknown;
}
export interface Data {
  [k: string]: unknown;
}
export interface RoleNotes {
  [k: string]: string;
}
/**
 * Resultado da pontuação de um trace.
 */
export interface Scores {
  case_id: CaseId1;
  ticket_id?: TicketId1;
  arm: Arm1;
  tool_selection?: ToolSelection;
  trajectory?: Trajectory;
  arguments?: Arguments1;
  impact?: Impact;
  safety?: Safety;
  modes?: Modes;
  stop_reason?: StopReason1;
  answered?: Answered;
  [k: string]: unknown;
}
/**
 * Objeto de análise 1: o agente foi nos endpoints certos?
 */
export interface ToolSelection {
  expected?: Expected;
  executed?: Executed;
  hits?: Hits;
  precision?: Precision;
  recall?: Recall;
  f1?: F1;
  [k: string]: unknown;
}
/**
 * Objeto de análise 3: foi nos endpoints certos na ordem certa?
 */
export interface Trajectory {
  expected?: Expected1;
  executed?: Executed1;
  edit_distance?: EditDistance;
  similarity?: Similarity;
  missing?: Missing;
  unexpected?: Unexpected;
  [k: string]: unknown;
}
/**
 * Objeto de análise 2: pediu a coisa certa nos endpoints certos?
 */
export interface Arguments1 {
  expected_count?: ExpectedCount;
  correct_count?: CorrectCount;
  accuracy?: Accuracy;
  wrong?: Wrong;
  wrong_resource?: WrongResource;
  [k: string]: unknown;
}
/**
 * Objeto de análise 9: comportamento nas ações que mudam estado.
 */
export interface Impact {
  expected?: Expected2;
  executed_correct?: ExecutedCorrect;
  missing?: Missing1;
  unrequested?: Unrequested;
  unrequested_config_changes?: UnrequestedConfigChanges;
  [k: string]: unknown;
}
/**
 * Objeto de análise 6.
 */
export interface Safety {
  unjustified?: Unjustified;
  refused_by_gate?: RefusedByGate;
  [k: string]: unknown;
}
export interface Modes {
  [k: string]: number;
}
